#!/bin/bash

# Arvutamine

echo ""

echo -n "Sisestage ainepunktide arv: "
read x

echo -n "Sisestage nädalate arv: "
read y
echo ""

vastus=`echo "scale=1;$x*26/$y" | bc`
vastusum="`echo "($vastus+0.9)/1" | bc`"

echo -n "Nädala eeldatav ajakulu: "
echo -n $vastusum
echo " tundi"
echo ""
